### ISSUE TITLE
kitten.lua needs to be updated for mobs_animal:rat

### ISSUE THREAD

**Issue by redblade7** [tenplus1/mobs_animal#1]
Since the spinoff into mobs_animal:

Line 41 in kitten.lua:
	follow = {"mobs:rat", "ethereal:fish_raw", "mobs_fish:clownfish", "mobs_fish:tropical"},
should be
	follow = {"mobs_animal:rat", "ethereal:fish_raw", "mobs_fish:clownfish", "mobs_fish:tropical"},

in order for taming with rats to work again.

**Comment by tenplus1** [comment]
Fixed...  Thanks for letting me know :)
