### ISSUE TITLE
Animal Mobs have no fall damage

### ISSUE THREAD

**Issue by RastaTux** [tenplus1/mobs_animal#20]
Hey,

i checked this mod with the newest minetest version (0.4.16) and at least sheep had no fall damage (it fell down from a very high cliff), as well as they don't fear height which is a bit strange as i don't think sheep wouldn't mind falling off a gap...

**Comment by tenplus1** [comment]
Fall damage working ok here, sheep go splat!  It may have had that little bit extra health to survive fall.

**Comment by RastaTux** [comment]
Som questions regarding this:
- Maybe it is off by default in creative mode?
- Does it depend in this "damage on" checkbox of minetest?
- In creative mode, minetest shows "immortality=1" for the sheeps, does that matter?
