### ISSUE TITLE
Random sheep can't be sheared

### ISSUE THREAD

**Issue by mtango688** [tenplus1/mobs_animal#23]
Just wandering a new world and made shears, but they turn out to be useless till you tame a sheep? Seems a little counterintuitive.

**Comment by AntumDeluge** [comment]
Just out of curiosity, are you using the correct shears? I know there is another mod that has shears that is not compatible with *mobs_animal* sheep.

**Comment by mtango688** [comment]
No, it definitely is this mod. I have no other use for shears, and when I commented out the line that does "name ~= self.owner" in sheep.lua it then worked as expected.

**Comment by tenplus1** [comment]
I made it so that killing random sheep give 1 wool only and you have to TAME a sheep so it lets you shear it to give 1-3 wool.
